---

# open_world_dataset: "../generalisability-analysis/results/open-world-dataset.hdf"
open_world_dataset: "small-test-dataset.hdf"

# Splitting strategies
strategies: ["dwr", "rr", "wr"]

# Splitting frequency
freqs: [100]

# Number of paths to split down
n_paths: [2, 3, 5]
