configfile: "config.yaml"

localrules: default

rule default:
    """Run all rules necessary to create all the desired defended datasets."""
    input:
        expand("results/dataset-{strategy}-{freq}-{npaths}.hdf",strategy=config["strategies"], freq=config["freqs"], npaths=config["n_paths"])


rule create_splits:
    """Create the splits that will be used for evaluation."""
    input:
        config["open_world_dataset"]
    output:
        "results/dataset-{strategy}-{freq}-{npaths}.hdf"
    log:
        "results/dataset-{strategy}-{freq}-{npaths}.log"
    params:
        strategy="{strategy}",
        freq="{freq}",
        npaths="{npaths}",
    wildcard_constraints:
        strategy="rr|wr|136r",
        freq="\d+",
        npaths="\d+",
    shell: """\
        ./split_traffic.py --freq {params.freq} --strategy {params.strategy} --n-paths {params.npaths} {input} {output} 2> {log}
        """
